### ISSUE TITLE
Question: adding new tweet to already existing thread?

### ISSUE THREAD

**Issue by Julianoe** [iyanuashiri/twitter-threader#1]
Interesting and thanks for sharing your code! I was wondering if you ever tried to use the twitter API to easily push a new tweet to an existing thread?

**Comment by iyanuashiri** [comment]
Hi. You are welcome. Yes, you can. The function `post_thread` has a `in_reply_to_status_id` parameter. You use the status id for an existing thread. 

https://github.com/iyanuashiri/twitter-threader/blob/e914e082e396f3fb525705e9290010093f632f6a/threader.py#L35
